feat: add pireps/latest endpoint
invernyx/smartcars-3-phpvms7-api pull request #15
Opened 2024-09-03 18:30 UTC by Thien42

@BossOfGames can you confirm if this would be the right approach to only fetch the latest pirep from a user?

I also want to make sure the response is an object and not an array.
I don't really have a way to test this at the moment, so thanks for your help!

2024-09-04 07:14 UTC, BossOfGames commented
Yes, but there's a better way of doing it.
`$user->latest_pirep`

If you look at the \App\Model\User Model, you'll see a relationship setup for the latest pirep. I believe that code is what powers the latest pirep widget on the `/dashboard` for phpVMS.

2024-09-05 19:36 UTC, Thien42 commented
@BossOfGames thanks! Fixed the PR.

2024-09-06 04:52 UTC, BossOfGames commented
I noticed that there wasn't a change made to the `/Http/Routes/api.php`

The route must be added here before it can be called by smartCARS, otherwise the call will fail outright with a 404 error.

2024-09-06 04:57 UTC, BossOfGames requested changes

2024-09-06 04:57 UTC, BossOfGames commented on Http/Controllers/Api/PirepsController.php
>          $user = User::find($request->get('pilotID'));
Is this meant to only be accessed by the current user? Or to grab any user's latest pirep? If it's only for the logged in user, do:

`$user = Auth::user();`

2024-09-06 04:57 UTC, BossOfGames commented on Http/Controllers/Api/PirepsController.php
>      public function latest(Request $request)
Route must be added to `/Http/Routes/api.php` otherwise there will be a 404 error.

2024-09-07 00:02 UTC, BossOfGames approved these changes

2024-11-24 04:56 UTC, merged